# Generated by Django 3.0.3 on 2020-02-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cate',
            table='cate',
        ),
    ]
