# Generated by Django 3.0.3 on 2020-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0002_auto_20200211_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
