# Generated by Django 3.0.3 on 2020-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
