# Generated by Django 3.0.3 on 2020-02-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0006_registration_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
