# Generated by Django 3.0.3 on 2020-02-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0007_auto_20200217_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofsubcate', models.CharField(max_length=100)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findusapp.Cate')),
            ],
            options={
                'db_table': 'subcate',
            },
        ),
    ]
