# Generated by Django 3.0.3 on 2020-02-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0008_subcate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcate',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findusapp.Cate'),
        ),
    ]
